name: CIbackend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/**'

jobs:
  instalarDependeciasBackend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/
    steps:
      - uses : actions/checkout@v6
      - uses : actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - run: npm ci

  pruebas:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/
    steps:
      - uses : actions/checkout@v6
      - uses : actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      #- run: cd backend/  #AAAAAAAAA
      - run: npm ci
      - run: npm test -- --coverage
  
  #verificar error de linter, ver linetr desp!
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/
    steps:
      - uses : actions/checkout@v6
      - uses : actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'
      - run: npm ci
      - run: npm run lint

